default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'postgres'
  password: '1234567'

development:
  <<: *default
  database: vida_saludable_dev

test:
  <<: *default
  database: vida_saludable_test

production:
  <<: *default
  database: vida_saludable_prod
